source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'HiPayFullservice_Example' do
  pod 'HiPayFullservice', :path => '../'
  #pod 'HiPayFullservice/Datecs-POS', :path => '../'

  target 'HiPayFullservice_Tests' do
  	 inherit! :search_paths

     pod 'HiPayFullservice', :path => '../'
	 pod 'OCMock'
	 pod 'OHHTTPStubs' , '~> 8.0.0'
  end
end

post_install do |installer|
  system("python ../deployment/generate_parameters.py")
end
