source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HiPayTPP_Example', :exclusive => true do
  pod "HiPayTPP", :path => "../"
end

target 'HiPayTPP_Tests', :exclusive => true do
  pod "HiPayTPP", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'Expecta+Snapshots'
end
