source 'https://github.com/CocoaPods/Specs.git'

target 'HiPayTPP_Example', :exclusive => true do
  pod "HiPayTPP", :path => "../"
  pod 'OHHTTPStubs'
end

target 'HiPayTPP_Tests', :exclusive => true do
  pod "HiPayTPP", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'Expecta+Snapshots'
  pod 'OCMock'
  pod 'OHHTTPStubs'
end
