stages:
  - review
  
include:
  - component: $CI_SERVER_FQDN/common/ci-components/ai-review-component/ai-review@1.0.0
    inputs:
      project_id: $AI_REVIEW_GCP_PROJECT_ID
      gitlab_private_token: $AI_REVIEW_GITLAB_TOKEN
      vertex_ai_sa: $AI_REVIEW_SA
      jira_user: $JIRA_API_EMAIL
      jira_token: $JIRA_API_TOKEN
