default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Set environment variables"
  lane :SetEnv do
    # Sed API Data
    system 'sed -i -e "s#$API_DATA_URL_STAGE#$API_DATA_URL_DEV#" ../HiPayFullservice/Core/Monitoring/HPFStats.m'
  end

  desc "Run tests"
  lane :Test do
    scan
  end

  desc "Build demo application"
  lane :BuildDemo do
    # Sync certificates and profiles
    match

    # Set Build Number
    set_info_plist_value(
      path: "Example/HiPayFullservice/HiPayFullservice-Info.plist",
      key: "CFBundleVersion",
      value: ENV['CIRCLE_BUILD_NUM']
    )

    set_info_plist_value(
      path: "Example/HiPayFullservice/HiPayFullservice-Info.plist",
      key: "CFBundleDisplayName",
      value: "HiPay Demo ("+ git_branch.gsub(/[^a-zA-Z0-9\-]/,"") + ")"
    )
    
    # Sed API Data
    system 'sed -i -e "s#$API_DATA_URL_STAGE#$API_DATA_URL_QA#" ../HiPayFullservice/Core/Monitoring/HPFStats.m'

    #Build app
    gym
  end

  desc "Deploy demo on AppCenter"
  lane :DeployDemo do
    appcenter_upload(
      api_token: ENV['APPCENTER_TOKEN'],
      owner_type: "organization", # organization = HiPay
      owner_name: "hipay-com", # See "Organization URL" in appCenter settings (https://appcenter.ms/orgs/hipay-com/)
      app_name: "HiPayDemo-" + git_branch.gsub(/[^a-zA-Z0-9\-]/,""),
      destinations: "Internal", # Distribution group named "Internal"
      destination_type: "group",
      file: "HiPay Demo.ipa",
      app_os: "iOS",
      app_platform: "Objective-C-Swift"
    )
  end

  desc "Deploy HiPayFullservice on Cocoapods"
  lane :DeployHiPayFullservice do
    # Set version number (e.g 1.0.0)
    version = "2.1.0"

    # Set version in PodSpec file 
    version_bump_podspec(path: "HiPayFullservice.podspec", version_number: version)

    # Check PodSpec file
    system "pod lib lint ../HiPayFullservice.podspec"

    # Deploy the Podspec to Trunk and make it publicly available
    system "pod trunk push --allow-warnings --skip-import-validation --skip-tests ../HiPayFullservice.podspec --verbose"

  end
end
