//
//  HPFCardTokenPaymentMethodRequest.h
//  Pods
//
//  Created by Jonathan TIRET on 14/10/2015.
//
//

#import "HPFAbstractPaymentMethodRequest.h"
#import "HPFTransaction.h"

typedef NS_ENUM(NSInteger, HPFAuthenticationIndicator) {
    HPFAuthenticationIndicatorUndefined = NSIntegerMax,
    HPFAuthenticationIndicatorBypass = 0,
    HPFAuthenticationIndicatorIfAvailable = 1,
    HPFAuthenticationIndicatorMandatory = 2,
};

/**
 *  Describes payment card information to be sent alongside an order request.
 */
@interface HPFCardTokenPaymentMethodRequest : HPFAbstractPaymentMethodRequest

/**
 *  The card token generated by the Secure Vault.
 */
@property (nonatomic, copy) NSString *cardToken;

/**
 *  Electronic Commerce Indicator (ECI).
 *  The ECI indicates the security level at which the payment information is processed between the cardholder and merchant.
 */
@property (nonatomic) HPFECI eci;

/**
 *  Indicates if the 3-D Secure authentication should be performed.
 */
@property (nonatomic) HPFAuthenticationIndicator authenticationIndicator;

/**
 *  Instantiate a card token request, to be sent alongside an order request.
 *
 *  @param token                   The card token generated by the Secure Vault.
 *  @param eci                     Electronic Commerce Indicator (ECI).
 *  @param authenticationIndicator Indicates if the 3-D Secure authentication should be performed.
 *
 *  @return A new card token request.
 */
+ (instancetype)cardTokenPaymentMethodRequestWithToken:(NSString *)token eci:(HPFECI)eci authenticationIndicator:(HPFAuthenticationIndicator)authenticationIndicator;

@end
