//
//  HPFThreeDSecure.h
//  Pods
//
//  Created by Jonathan TIRET on 09/10/2015.
//
//

#import <Foundation/Foundation.h>

/**
 *  Describes a 3-D Secure enrollment status.
 */
typedef NS_ENUM(char, HPFThreeDSecureEnrollmentStatus) {

    /**
     *  Unknown enrollment status.
     */
    HPFThreeDSecureEnrollmentStatusUnknown = ' ',

    /**
     *  Card is enrolled in the 3-D Secure program and the payer is eligible for authentication processing.
     */
    HPFThreeDSecureEnrollmentStatusAuthenticationAvailable = 'Y',
    
    /**
     *  Card is not enrolled in 3-D Secure program. Chargeback Liability Shift: If the cardholder later disputes the purchase, the issuer may not submit a chargeback to the merchant.
     */
    HPFThreeDSecureEnrollmentStatusCardholderNotEnrolled = 'N',
    
    /**
     *  The card associations were unable to verify if the cardholder is enrolled in the 3- D Secure program.
     *  Merchants can choose to accept the card nonetheless and proceed the purchase as non-authenticated when submitting the authorization.
     *  Chargeback Liability Shift: The Acquirer/Merchant retains liability if the cardholder later disputes making the purchase.
     */
    HPFThreeDSecureEnrollmentStatusUnableToAuthenticate = 'U',
    
    /**
     *  An error occurred during the enrollment verification process.
     *  Chargeback Liability Shift: The card can be accepted for authorization processing, yet the merchant may not claim a liability shift on this transaction in case of a dispute with the cardholder.
     */
    HPFThreeDSecureEnrollmentStatusOtherError = 'E',
};


/**
 *  Describes a 3-D Secure authentication status.
 */
typedef NS_ENUM(char, HPFThreeDSecureAuthenticationStatus) {

    /**
     *  Authentication status unknown.
     */
    HPFThreeDSecureAuthenticationStatusUnknown = ' ',
    
    /**
     *  Cardholder was successfully authenticated. The Issuer has authenticated the cardholder by verifying the identity information or password.
     */
    HPFThreeDSecureAuthenticationStatusSuccessful = 'Y',
    
    /**
     *  Authentication could not be performed but a proof of authentication attempt was provided.
     */
    HPFThreeDSecureAuthenticationStatusAttempted = 'A',
    
    /**
     *  The Issuer is not able to complete the authentication request due to a technical error or other problem.
     *  Possible reasons include:
     *  - Invalid type of card such as a Commercial Card or any anonymous Prepaid Card.
     *  - Unable to establish an SSL session with cardholder browser.
     */
    HPFThreeDSecureAuthenticationStatusCouldNotBePerformed = 'U',
    
    /**
     *  The cardholder did not complete authentication and the card should not be accepted for payment.
     *  The following are reasons to fail an authentication:
     *  - Cardholder fails to correctly enter the authentication information
     *  - Cardholder cancels the authentication process.
     *  An authentication failure may be a possible indication of a fraudulent user.
     *  Authorization request should not be submitted.
     */
    HPFThreeDSecureAuthenticationStatusAuthenticationFailed = 'N',
    
    /**
     *  An error occurred during the authentication process. Authorization request should not be submitted.
     */
    HPFThreeDSecureAuthenticationStatusOther = 'E',
};

/**
 *  Describes the result of the 3-D Secure Authentication.
 */
@interface HPFThreeDSecure : NSObject

/**
 *  The enrollment status.
 */
@property (nonatomic, readonly) HPFThreeDSecureEnrollmentStatus enrollmentStatus;

/**
 *  The enrollment message.
 */
@property (nonatomic, readonly, nonnull) NSString *enrollmentMessage;

/**
 *  The authentication status. This field is only included if payment authentication was attempted and a value was received.
 */
@property (nonatomic, readonly) HPFThreeDSecureAuthenticationStatus authenticationStatus;

/**
 *  The authentication message. This field is only included if payment authentication was attempted and a value was received.
 */
@property (nonatomic, readonly, nullable) NSString *authenticationMessage;

/**
 *  This is a value generated by the card issuer as a token to prove that the cardholder was successfully authenticated.
 */
@property (nonatomic, readonly, nullable) NSString *authenticationToken;

/**
 *  A unique transaction identifier that is generated by the payment server on behalf of the merchant to identify the 3-D Secure transaction.
 */
@property (nonatomic, readonly, nullable) NSString *xid;

@end
