name: iOS Pipeline

on: [push]

jobs:
  tests:
    runs-on: macos-latest
    environment: stage
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'

      - name: Install Dependencies
        run: gem install bundler && bundle install

      - name: Install pods
        run: pod install --project-directory=Example/

      - name: Tests
        run: fastlane Test

  build_demo:
    needs: tests
    runs-on: macos-latest
    environment: stage
    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      HIPAY_FULLSERVICE_API_PRODUCTION_PASSWORD: ${{ secrets.HIPAY_FULLSERVICE_API_PRODUCTION_PASSWORD }}
      HIPAY_FULLSERVICE_API_PRODUCTION_USERNAME: ${{ secrets.HIPAY_FULLSERVICE_API_PRODUCTION_USERNAME }}
      HIPAY_FULLSERVICE_API_STAGE_PASSWORD: ${{ secrets.HIPAY_FULLSERVICE_API_STAGE_PASSWORD }}
      HIPAY_FULLSERVICE_API_STAGE_USERNAME: ${{ secrets.HIPAY_FULLSERVICE_API_STAGE_USERNAME }}
      HIPAY_FULLSERVICE_PRODUCTION_SECRET_PASSPHRASE: ${{ secrets.HIPAY_FULLSERVICE_PRODUCTION_SECRET_PASSPHRASE }}
      HIPAY_FULLSERVICE_STAGE_SECRET_PASSPHRASE: ${{ secrets.HIPAY_FULLSERVICE_STAGE_SECRET_PASSPHRASE }}
      HIPAY_PRODUCTION_APPLE_PAY_MERCHANT_IDENTIFIER: ${{ secrets.HIPAY_PRODUCTION_APPLE_PAY_MERCHANT_IDENTIFIER }}
      HIPAY_PRODUCTION_APPLE_PAY_PRIVATE_KEY_PASSWORD: ${{ secrets.HIPAY_PRODUCTION_APPLE_PAY_PRIVATE_KEY_PASSWORD }}
      HIPAY_PRODUCTION_APPLE_PAY_USERNAME: ${{ secrets.HIPAY_PRODUCTION_APPLE_PAY_USERNAME }}
      HIPAY_STAGE_APPLE_PAY_MERCHANT_IDENTIFIER: ${{ secrets.HIPAY_STAGE_APPLE_PAY_MERCHANT_IDENTIFIER }}
      HIPAY_STAGE_APPLE_PAY_PRIVATE_KEY_PASSWORD: ${{ secrets.HIPAY_STAGE_APPLE_PAY_PRIVATE_KEY_PASSWORD }}
      HIPAY_STAGE_APPLE_PAY_USERNAME: ${{ secrets.HIPAY_STAGE_APPLE_PAY_USERNAME }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'

      - name: Install Dependencies
        run: gem install bundler && bundle install

      - name: Install pods
        run: pod install --project-directory=Example/

      - name: Build-demo
        run: fastlane BuildDemo

      - name: Save .ipa in artifact
        uses: actions/upload-artifact@v3
        with:
          name: HiPay Demo.ipa
          path: HiPay Demo.ipa

  deploy_demo:
    needs: build_demo
    runs-on: macos-latest
    environment: stage
    env:
      APPCENTER_TOKEN: ${{ secrets.APPCENTER_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'

      - name: Install Dependencies
        run: gem install bundler && bundle install

      - name: Download .ipa from previous job
        uses: actions/download-artifact@v3
        with:
          name: HiPay Demo.ipa

      - name: Deploy-demo
        run: fastlane DeployDemo
